CREATE TABLE PROPIETARIO(
	ID_PROP INT (10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    DIRECCION VARCHAR (50),
    TELEFONO VARCHAR(9),
    EMAIL VARCHAR(50),
    CONSTRAINT ID_PROP PRIMARY KEY (ID_PROP)
);

CREATE TABLE VEHICULO (
	ID_VEHI INT (10) NOT NULL AUTO_INCREMENT,
    MARCA VARCHAR (30) NOT NULL,
    MODELO VARCHAR (30) NOT NULL,
    ANHO DECIMAL (4.0),
    MOTOR VARCHAR (20),
    CHASIS VARCHAR (17),
    ID_PROP INT (10) NOT NULL,
    CONSTRAINT ID_VEHI PRIMARY KEY (ID_VEHI),
    CONSTRAINT FK_VEHI_PROP FOREIGN KEY (ID_PROP) REFERENCES PROPIETARIO (ID_PROP)
);

CREATE TABLE AVERIA (
    ID_AVERIA INT (10) NOT NULL AUTO_INCREMENT,
    ID_VEHI INT (10) NOT NULL,
    FECHA_AVERIA DATE,
    COMEN_AVERIA VARCHAR (100) NOT NULL,
    PRECIO_REPUESTO DECIMAL (7,2),
    PRECIO_COBRADO DECIMAL (7,2),
    KM_ACTUAL DECIMAL (7,0),
    CONSTRAINT PK_ID_AVERIA PRIMARY KEY (ID_AVERIA),
    CONSTRAINT FK_AVERIA_VEHI FOREIGN KEY (ID_VEHI) REFERENCES VEHICULO (ID_VEHI)
);

CREATE TABLE USUARIO (
    USUARIO VARCHAR (30) NOT NULL,
    CONTRASENHA VARCHAR (50) NOT NULL,
    PRIVILEGIO VARCHAR(1) NOT NULL DEFAULT '1',
    CONSTRAINT PK_USUARIO PRIMARY KEY (USUARIO)
);


CREATE TABLE TIPO_ALARMA (
    NOMBRE VARCHAR (30) NOT NULL,
    MESES_EXP DECIMAL (4,0),
    KM_EXP DECIMAL (7,0),
    CONSTRAINT PK_TIPO_ALARMA_NOMBRE PRIMARY KEY (NOMBRE) 
);

CREATE TABLE ALARMA (
    ID_VEHI INT (10) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FECHA_ALARMA DATE NOT NULL,
    KM_ACTUAL DECIMAL (7,0),
    CONSTRAINT PK_ID_VEHI_COD_ALARMA PRIMARY KEY (ID_VEHI,NOMBRE),
    CONSTRAINT FK_ALARMA_VEHI FOREIGN KEY (ID_VEHI) REFERENCES VEHICULO (ID_VEHI),
    CONSTRAINT FK_ALARMA_NOMBRE FOREIGN KEY (NOMBRE) REFERENCES TIPO_ALARMA (NOMBRE)
);

